'use client';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/api';
import { Badge, Button, Card, ErrorBanner, Field, inputClass, LinkButton, PageLoading, SectionTitle } from './ui';
import { ConfirmationModal } from './confirmation-modal';
import { OrderStatusBadge } from './status-badge';
import type { OrderStatus } from '@/lib/types';
import { formatDate, formatNumber, formatToman } from '@/lib/format';
export type OrganizationPlan = { id: string; name: string; seats: number; ordersPerPeriod: number; durationDays: number; feeToman: number; active: boolean };
type Member = { id: string; role: string; status: string; teamId: string | null; user: { fullName: string } };
type Team = { id: string; name: string };
type Org = { id: string; name: string; membership: { id: string; role: string; teamId: string | null }; teams: Team[]; members: Member[]; requestedPlan: null | { name: string }; subscription: null | { planName: string; startsAt: string; endsAt: string; seats: number; ordersPerPeriod: number; active: boolean }; usedOrders: number };
type Order = { id: string; code: string; title: string; status: OrderStatus; version: number; organizationId: string | null };
type Pending = { path: string; method: 'POST' | 'PATCH'; body: Record<string,unknown>; title: string; description: string };
const roleLabel: Record<string,string> = { owner: 'مالک', manager: 'مدیر', member: 'عضو' };
function workspaceData(id: string, page: number, signal?: AbortSignal) {
 return Promise.all([apiFetch<Org>(`/customer/organizations/${id}`, { signal, dedupe: false }), apiFetch<{ items: Order[]; total: number }>(`/customer/organizations/${id}/orders?page=${page}`, { signal, dedupe: false }), apiFetch<Order[]>('/customer/orders?status=draft&pageSize=100', { signal, dedupe: false }), apiFetch<OrganizationPlan[]>('/customer/organizations/plans', { signal, dedupe: false })]);
}
export function OrganizationWorkspace({ id }: { id: string }) {
 const [data, setData] = useState<Awaited<ReturnType<typeof workspaceData>> | null>(null);
 const [page, setPage] = useState(1); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
 const [teamName, setTeamName] = useState(''); const [phone, setPhone] = useState(''); const [inviteRole, setInviteRole] = useState('member'); const [inviteTeam, setInviteTeam] = useState(''); const [planId, setPlanId] = useState(''); const [draftId, setDraftId] = useState(''); const [orderTeam, setOrderTeam] = useState(''); const [pending, setPending] = useState<Pending | null>(null);
 const base = `/customer/organizations/${id}`;
 useEffect(() => { const c = new AbortController(); workspaceData(id, page, c.signal).then(setData).catch(e => { if (!c.signal.aborted) setError(e instanceof Error ? e.message : 'اطلاعات سازمان دریافت نشد.'); }); return () => c.abort(); }, [id,page]);
 async function run(path: string, body: Record<string,unknown>, method: 'POST' | 'PATCH' = 'POST') { setBusy(true); setError(''); setMessage(''); try { await apiFetch(path, { method, body }); setData(await workspaceData(id,page)); setMessage('تغییر با موفقیت ثبت شد.'); } catch(e) { setError(e instanceof Error ? e.message : 'عملیات انجام نشد.'); } finally { setBusy(false); setPending(null); } }
 if (!data) return <><SectionTitle>فضای سازمانی</SectionTitle>{error ? <ErrorBanner message={error} /> : <PageLoading />}</>;
 const [org, orders, drafts, plans] = data;
 const owner = org.membership.role === 'owner'; const manager = owner || org.membership.role === 'manager';
 const availableDrafts = drafts.filter(row => !row.organizationId);
 return <div className="space-y-5"><SectionTitle subtitle={`نقش شما: ${roleLabel[org.membership.role]}`}>{org.name}</SectionTitle><LinkButton href="/organizations" variant="secondary">همه سازمان‌ها و دعوت‌ها</LinkButton>
 {error && <ErrorBanner message={error} />}{message && <p role="status" className="text-sm text-success">{message}</p>}
 <Card><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold">اشتراک سازمان</h2><Badge color={org.subscription?.active ? 'green' : 'yellow'}>{org.subscription?.active ? 'فعال' : 'نیازمند فعال‌سازی یا تمدید'}</Badge></div>{org.subscription && <div className="mt-4 space-y-2 text-sm leading-7"><p>{org.subscription.planName} · تا {formatDate(org.subscription.endsAt)}</p><p>اعضا: حداکثر {formatNumber(org.subscription.seats)} نفر · سهمیه سفارش این دوره: {formatNumber(org.usedOrders)} از {formatNumber(org.subscription.ordersPerPeriod)}</p></div>}
 {owner && <form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); void run(`${base}/plan-request`, { planId }); }}><Field label="درخواست پلن یا تمدید"><select className={inputClass} value={planId} onChange={e => setPlanId(e.target.value)} required><option value="">انتخاب پلن</option>{plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name} · {formatToman(plan.feeToman)} · {formatNumber(plan.durationDays)} روز</option>)}</select></Field><Button disabled={busy || !planId}>ارسال درخواست به مالی</Button></form>}
 {org.requestedPlan && <p className="mt-3 text-sm text-fg-muted">درخواست در صف بررسی مالی: {org.requestedPlan.name}</p>}
 <p className="mt-3 text-xs leading-7 text-fg-muted">درخواست پلن باعث برداشت وجه نمی‌شود. فعال‌سازی بر اساس قرارداد و تأیید واحد مالی است؛ تمدید و پرداخت خودکار فعال نیست.</p></Card>
 <div className="grid gap-5 lg:grid-cols-2">
 {manager && <Card><h2 className="mb-4 font-bold">تیم‌های سازمان</h2><div className="mb-4 flex flex-wrap gap-2">{org.teams.map(team => <Badge key={team.id}>{team.name}</Badge>)}</div><form className="space-y-3" onSubmit={e => { e.preventDefault(); void run(`${base}/teams`, { name: teamName.trim() }); }}><Field label="نام تیم جدید"><input className={inputClass} required minLength={2} maxLength={100} value={teamName} onChange={e => setTeamName(e.target.value)} /></Field><Button disabled={busy || !org.subscription?.active}>ایجاد تیم</Button></form></Card>}
 {owner && <Card><h2 className="mb-4 font-bold">دعوت عضو</h2><form className="space-y-3" onSubmit={e => { e.preventDefault(); void run(`${base}/invitations`, { phone, role: inviteRole, ...(inviteTeam ? { teamId: inviteTeam } : {}) }); }}><Field label="موبایل حساب ثبت‌شده"><input dir="ltr" autoComplete="off" className={inputClass} required maxLength={100} value={phone} onChange={e => setPhone(e.target.value)} /></Field><Field label="نقش دعوت‌شده"><select className={inputClass} value={inviteRole} onChange={e => setInviteRole(e.target.value)}><option value="member">عضو یک تیم</option><option value="manager">مدیر همه تیم‌ها</option></select></Field><TeamSelect label="تیم دعوت‌شده" teams={org.teams} value={inviteTeam} onChange={setInviteTeam} /><Button disabled={busy || !org.subscription?.active}>ارسال دعوت</Button></form><p className="mt-3 text-xs leading-7 text-fg-muted">دعوت فقط پس از پذیرش گیرنده فعال می‌شود. دعوت باز نیز از ظرفیت پلن استفاده می‌کند.</p></Card>}
 </div>
 <Card><h2 className="mb-4 font-bold">اعضای قابل مشاهده</h2><div className="grid gap-3 lg:grid-cols-2">{org.members.map(member => <div key={`${member.id}-${member.role}-${member.teamId}`} className="rounded-control border border-border p-4"><h3 className="font-bold">{member.user.fullName}</h3><p className="my-2 text-sm text-fg-muted">{roleLabel[member.role]} · {member.status === 'invited' ? 'دعوت باز' : 'فعال'} · {org.teams.find(team => team.id === member.teamId)?.name ?? 'بدون تیم'}</p>{owner && member.role !== 'owner' && <MemberControls member={member} teams={org.teams} busy={busy} onRequest={(body) => setPending({ path: `${base}/members/${member.id}`, method: 'PATCH', body, title: 'تغییر دسترسی عضو', description: 'سطح دسترسی به اطلاعات همین سازمان تغییر می‌کند؛ مالکیت مالی سفارش‌های شخصی تغییر نمی‌کند.' })} onTransfer={() => setPending({ path: `${base}/transfer-owner`, method: 'POST', body: { memberId: member.id }, title: 'انتقال مالکیت سازمان', description: 'شما مدیر می‌شوید و این عضو فعال مالک سازمان خواهد شد.' })} />}</div>)}</div><p className="mt-4 text-xs text-fg-muted">عضو معمولی فقط هم‌تیمی‌های خود را می‌بیند. هیچ شماره تلفن یا ایمیلی در این فهرست نمایش داده نمی‌شود.</p></Card>
 <Card><h2 className="mb-4 font-bold">افزودن پیش‌نویس شخصی به سازمان</h2><form className="grid items-end gap-3 lg:grid-cols-3" onSubmit={e => { e.preventDefault(); const draft = availableDrafts.find(row => row.id === draftId); if (draft) setPending({ path: `${base}/orders`, method: 'POST', body: { orderId: draft.id, version: draft.version, ...(orderTeam || (!manager && org.membership.teamId) ? { teamId: orderTeam || org.membership.teamId } : {}) }, title: 'اشتراک خلاصه سفارش با سازمان', description: 'عنوان و وضعیت سفارش برای اعضای مجاز سازمان قابل مشاهده می‌شود. فایل‌ها، پیام‌ها، فاکتور و پرداخت همچنان فقط متعلق به شما هستند. اتصال به سازمان در این نسخه قابل بازگردانی نیست.' }); }}><Field label="پیش‌نویس متعلق به شما"><select className={inputClass} required value={draftId} onChange={e => setDraftId(e.target.value)}><option value="">انتخاب پیش‌نویس</option>{availableDrafts.map(row => <option key={row.id} value={row.id}>{row.code} · {row.title}</option>)}</select></Field><TeamSelect label="تیم سفارش" teams={manager ? org.teams : org.teams.filter(team => team.id === org.membership.teamId)} value={orderTeam} onChange={setOrderTeam} /><Button disabled={busy || !draftId || !org.subscription?.active}>بررسی و اتصال سفارش</Button></form><p className="mt-3 text-xs text-fg-muted">تا ۱۰۰ پیش‌نویس اخیر نمایش داده می‌شود. برای درخواست تازه از بخش ثبت سفارش شروع کنید.</p></Card>
 <Card><h2 className="mb-4 font-bold">خلاصه سفارش‌های مجاز</h2>{!orders.items.length ? <p className="text-sm text-fg-muted">هنوز سفارشی برای دسترسی شما در این سازمان وجود ندارد.</p> : <ul className="space-y-3">{orders.items.map(row => <li key={row.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-border py-3"><div><bdi className="text-xs text-fg-muted">{row.code}</bdi><p className="font-medium">{row.title}</p></div><OrderStatusBadge status={row.status} /></li>)}</ul>}<div className="mt-4 flex items-center gap-3"><Button variant="secondary" disabled={page <= 1 || busy} onClick={() => setPage(page - 1)}>قبلی</Button><span className="text-sm">صفحه {formatNumber(page)}</span><Button variant="secondary" disabled={page * 20 >= orders.total || busy} onClick={() => setPage(page + 1)}>بعدی</Button></div></Card>
 <ConfirmationModal key={pending?.path ?? 'closed'} open={pending !== null} title={pending?.title ?? ''} description={pending?.description ?? ''} impacts={['تصمیم و دلیل آن در سابقه حسابرسی ثبت می‌شود.']} confirmLabel="تأیید و ثبت" onCancel={() => setPending(null)} onConfirm={async note => { if (pending) await run(pending.path, { ...pending.body, note }, pending.method); }} />
 </div>;
}
function TeamSelect({ label, teams, value, onChange }: { label: string; teams: Team[]; value: string; onChange: (value: string) => void }) { return <Field label={label}><select className={inputClass} value={value} onChange={e => onChange(e.target.value)}><option value="">بدون تیم / تیم فعلی عضو</option>{teams.map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select></Field>; }
function MemberControls({ member, teams, busy, onRequest, onTransfer }: { member: Member; teams: Team[]; busy: boolean; onRequest: (body: Record<string,unknown>) => void; onTransfer: () => void }) {
 const [role, setRole] = useState(member.role); const [teamId, setTeamId] = useState(member.teamId ?? '');
 return <details className="mt-3"><summary className="cursor-pointer py-2 text-sm text-fg-muted">مدیریت عضویت</summary><div className="mt-3 space-y-3"><Field label={`نقش ${member.user.fullName}`}><select className={inputClass} value={role} onChange={e => setRole(e.target.value)}><option value="member">عضو</option><option value="manager">مدیر</option></select></Field><TeamSelect label={`تیم ${member.user.fullName}`} teams={teams} value={teamId} onChange={setTeamId} /><div className="flex flex-wrap gap-2">{member.status === 'active' && <Button variant="secondary" disabled={busy} onClick={() => onRequest({ role, status: 'active', teamId: teamId || null })}>تغییر نقش و تیم</Button>}<Button variant="danger" disabled={busy} onClick={() => onRequest({ role, status: 'revoked' })}>{member.status === 'invited' ? 'لغو دعوت' : 'لغو عضویت'}</Button>{member.status === 'active' && <Button variant="secondary" disabled={busy} onClick={onTransfer}>انتقال مالکیت</Button>}</div></div></details>;
}
